def document_key_mapper(user_data) -> dict:
    """this function map the data to conditional data and data to dynamically update in the doc"""

    data = {
        "<Insert #1>": user_data.get("first_name"),
        "<Insert #2>": user_data.get("last_name"),
    }

    conditional_data = {
        "#10": user_data.get("pregnant"),
        "#11": user_data.get("perimenopausal"),
        "#12": user_data.get("postmenopausal"),
        "#16": user_data.get("bmi"),
        "#17": user_data.get("lose_weight"),
        "#20": user_data.get("energy_level"),
        "#25": user_data.get("cups_of_caffeine_per_day"),
        "#26": user_data.get("willing_to_be_caffeine_free"),
        "#27": user_data.get("willing_to_change_to_decaf"),
        "#28": user_data.get("alcohol_nights_per_week"),
        "#29": user_data.get("alcohol_free_nights_per_week"),
        "#30": user_data.get("cups_of_water_per_day"),
        "#31": user_data.get("avoid_processed_foods"),
        "#33": user_data.get("can_follow_weekly_meal_plans"),
        "#34": user_data.get("can_carry_out_food_preparation"),
        "#35": user_data.get("diet_type"),
        "#36": user_data.get("willing_to_eat"),
        "#37": user_data.get("meals_per_day"),
        "#38": user_data.get("daily_meals_include"),
        "#39": user_data.get("food_intolerances_allergies"),
        "#40": user_data.get("foods_you_crave"),
        "#41": user_data.get("drink_sugary_drinks"),
        "#43": user_data.get("fitness_plan_type"),
        "#44": user_data.get("restorative_exercises"),
        "#45": user_data.get("challenging_exercises"),
        "#47": user_data.get("currently_exercising"),
        "#48": user_data.get("exercise_schedule"),
        "#49": user_data.get("exercise_time_per_day"),
        "#50": user_data.get("training_location"),
        "#51": user_data.get("has_personal_trainer"),
        "#52": user_data.get("personal_trainer_frequency"),
        "#55": user_data.get("increase_flexibility"),
        "#57": user_data.get("increase_strength"),
        "#59": user_data.get("increase_fitness"),
        "#60": user_data.get("physical_injuries"),
        "#62": user_data.get("mindfulness_stress_management_plan"),
        "#63": user_data.get("bedtime"),
        "#64": user_data.get("fall_asleep_easily"),
        "#66": user_data.get("difficult_to_get_back_to_sleep"),
        "#67": user_data.get("average_sleep_hours"),
        "#69": user_data.get("wake_up_feeling_rested"),
        "#71": user_data.get("challenging_to_unwind_after_work"),
        "#72": user_data.get("unwind_methods"),
        "#73": user_data.get("mental_health_rating"),
        "#78": user_data.get("enjoy_walking_for_exercise"),
        "#80": user_data.get("wellbeing_changes"),
        "#82": user_data.get("smoking"),
        "#85": user_data.get("on_medication"),
        "#87": user_data.get("digestive_health_problems"),
        "#89": user_data.get("diagnosed_health_concerns"),
        "#91": user_data.get("under_guidance_of_naturopath_dietician_nutritionist"),
    }
    return data, conditional_data
