from datetime import datetime


def table_filed_mapper(data: dict) -> dict:
    """
    Map table filed to db table filed
    """
    data_map = {
        "event_id": data.get('event_id'),
        "form_id": data.get('form_id'),
        "landed_at": datetime.fromisoformat(data.get("landed_at")),
        "submitted_at": datetime.fromisoformat(data.get("submitted_at")),
        "first_name": data.get('What is your first name?'),
        "last_name": data.get("What is your last name?"),
        "company_name": data.get("What is the name of the company that you work for?"),
        "company_tenure": data.get("How long have you worked for this company?"),
        "job_title": data.get("What is your job title?"),
        "location": data.get("Where are you located?"),
        "email": data.get("What is your email address?"),
        "phone_number": data.get("What is your phone number?"),
        "sex": data.get("What is your sex?"),
        "pregnant": data.get("Are you pregnant?"),
        "perimenopausal": data.get("Are you perimenopausal?"),
        "postmenopausal": data.get("Are you postmenopausal?"),
        "age": data.get("What is your age?"),
        "height": data.get("What is your height (cm)?"),
        "weight": data.get("What is your current weight (kg)?"),
        "bmi": data.get("What is your BMI? "),
        "lose_weight": data.get("Do you wish to lose weight?"),
        "weight_loss_goal": data.get("How much weight would you like to lose (kg)?"),
        "improve_body_composition": data.get
        ("Do you wish to improve your body composition (increase muscle and decrease body fat)?"),
        "energy_level": data.get("How much energy do you have each day?"),
        "stress_level": data.get("What is your level of stress at the moment?"),
        "sleep_duration": data.get("How many hours of sleep are you getting on average per night?"),
        "go_chemical_free": data.get("Are you interested in going chemical-free?"),
        "drink_caffeine": data.get("Do you drink caffeine via tea, coffee and/or energy drinks?"),
        "cups_of_caffeine_per_day": data.get("How many cups of caffeine do you drink per day?"),
        "willing_to_be_caffeine_free": data.get("Are you willing to be caffeine-free?"),
        "willing_to_change_to_decaf": data.get("Are you willing to change to decaffeinated coffee?"),
        "alcohol_nights_per_week": data.get("On average, how many nights per week do you drink alcohol?"),
        "alcohol_free_nights_per_week": data.get("How many nights are you willing to be alcohol-free?"),
        "cups_of_water_per_day": data.get("How many cups of water do you drink per day?"),
        "avoid_processed_foods": data.get("Are you willing to avoid processed foods?"),
        "interested_in_nutrition_plan": data.get
        ("*Nutrition*\nAre you interested in following our *Nutrition* plan throughout the program?"),
        "can_follow_weekly_meal_plans": data.get("Can you follow weekly meal plans for the next 16 weeks?"),
        "can_carry_out_food_preparation": data.get("Can you carry out food preparation each week?"),
        "diet_type": data.get("What is your diet type?"),
        "willing_to_eat": ", ".join(data.get("Are you willing to eat...")),
        "meals_per_day": data.get("How many meals do you currently eat per day?"),
        "daily_meals_include": ", ".join(data.get("Do your daily meals include...")),
        "food_intolerances_allergies": data.get("Do you have any food intolerances and/or allergies?"),
        "foods_you_crave": ", ".join(data.get("What foods do you crave?")),
        "drink_sugary_drinks": data.get
        ("Do you regularly drink sugary drinks, e.g. soft drink, cordial, frappés, etc?"),
        "interested_in_fitness_plan": data.get
        ("*Fitness*\nAre you interested in following our *Fitness* plan throughout the program?"),
        "fitness_plan_type": data.get("Will you be following our *Restorative* or *Challenging* exercises?"),
        "restorative_exercises": ", ".join(data.get
                                           ("When you do the *Restorative* exercise program, what exercises are you willing to do?")),
        "challenging_exercises": ", ".join(data.get
                                           ("When you do the *Challenging* exercise program, what exercises are you willing to do?")),
        "exercises_willing_to_do": ", ".join(data.get("What exercises are you willing to do?")),
        "currently_exercising": ", ".join(data.get("Are you currently exercising?")),
        "exercise_schedule": ", ".join(data.get("When do you plan to exercise each day?")),
        "exercise_time_per_day": data.get("How much time will you exercise per day?"),
        "training_location": data.get("Will you be training at a gym or home?"),
        "has_personal_trainer": data.get("Do you currently have a personal trainer?"),
        "personal_trainer_frequency": data.get("How many times per week do you see your personal trainer?"),
        "regular_yoga_practice": data.get("Do you currently do a regular yoga practice?"),
        "flexibility_rating": data.get("How would you rate your flexibility?"),
        "increase_flexibility": data.get("Do you wish to increase your flexibility?"),
        "strength_rating": data.get("How would you rate your strength?"),
        "increase_strength": data.get("Do you wish to increase your muscle and strength?"),
        "fitness_rating": data.get("How would you rate your general fitness?"),
        "increase_fitness": data.get("Do you wish to increase your fitness?"),
        "physical_injuries": data.get("Do you have any physical injuries?"),
        "injury_details": data.get("Please provide details about your physical injuries."),
        "mindfulness_stress_management_plan": data.get
        ("*Mindfulness & Stress Management*\nAre you interested in following our *Mindfulness & Stress Management* plan throughout the program?"),
        "bedtime": data.get("What time do you go to bed?"),
        "fall_asleep_easily": data.get("Do you fall asleep easily?"),
        "wake_up_during_night": data.get("Do you wake up during the night?"),
        "difficult_to_get_back_to_sleep": data.get("Do you find it difficult to get back to sleep?"),
        "average_sleep_hours": data.get("On average, how many hours of sleep do you get per night?"),
        "wake_up_time": data.get("What time do you wake up in the morning?"),
        "wake_up_feeling_rested": data.get("Do you wake up feeling rested and refreshed?"),
        "morning_energy_rating": data.get("How would you rate your energy in the morning?"),
        "challenging_to_unwind_after_work": data.get("Do you find it challenging to unwind after work?"),
        "unwind_methods": ", ".join(data.get("How do you unwind after work?")),
        "mental_health_rating": data.get("How would you rate your mental health?"),
        "incorporate_mindfulness": data.get("Would you like to incorporate mindfulness into your daily routine?"),
        "incorporate_stress_management": data.get
        ("Would you like to incorporate stress management into your daily routine?"),
        "incorporate_stretches": data.get("Would you like to incorporate stretches into your daily routine?"),
        "incorporate_meditation": data.get("Would you like to incorporate meditation into your daily routine?"),
        "enjoy_walking_for_exercise": data.get("Do you enjoy walking for exercise?"),
        "walking_time_per_day": data.get("How much time can you allocate to walking each day?"),
        "wellbeing_changes": ", ".join(data.get
                                       ("What change(s) would you like to work on over the next 16-weeks to enhance your personal wellbeing?")),
        "smoking": data.get("Do you smoke? "),
        "quit_smoking_desire": data.get("Would you like to quit smoking? "),
        "taking_supplements": data.get("Are you taking any supplements?"),
        "supplement_details": data.get("Please provide details about your supplements."),
        "on_medication": data.get("Are you on any medication?"),
        "medication_details": data.get("Please provide details about your medication."),
        "digestive_health_problems": data.get("Do you suffer from digestive health problems?"),
        "digestive_health_details": data.get("Please provide details about your digestive health problems."),
        "diagnosed_health_concerns": data.get("Do you have any diagnosed health concerns?"),
        "health_concern_details": data.get("Please provide details about your diagnosed health concerns."),
        "under_guidance_of_naturopath_dietician_nutritionist": data.get
        ("Are you currently under the guidance of a naturopath/dietician/nutritionist?"),
        "guidance_details": data.get("Please provide details about who, where and why."),
        "questions_or_concerns": data.get
        ("Please provide any other questions or concerns and we will address these in your consultation.")
    }
    return data_map


def get_data(raw_data):
    """map the data return from database to table."""
    data_map = {
        "event_id": raw_data[1],
        "form_id": raw_data[2],
        "landed_at": raw_data[3],
        "submitted_at": raw_data[4],
        "first_name": raw_data[5],
        "last_name": raw_data[6],
        "company_name": raw_data[7],
        "company_tenure": raw_data[8],
        "job_title": raw_data[9],
        "location": raw_data[10],
        "email": raw_data[11],
        "phone_number": raw_data[12],
        "sex": raw_data[13],
        "pregnant": raw_data[14],
        "perimenopausal": raw_data[15],
        "postmenopausal": raw_data[16],
        "age": raw_data[17],
        "height": raw_data[18],
        "weight": raw_data[19],
        "bmi": raw_data[20],
        "lose_weight": raw_data[21],
        "weight_loss_goal": raw_data[22],
        "improve_body_composition": raw_data[23],
        "energy_level": raw_data[24],
        "stress_level": raw_data[25],
        "sleep_duration": raw_data[26],
        "go_chemical_free": raw_data[27],
        "drink_caffeine": raw_data[28],
        "cups_of_caffeine_per_day": raw_data[29],
        "willing_to_be_caffeine_free": raw_data[30],
        "willing_to_change_to_decaf": raw_data[31],
        "alcohol_nights_per_week": raw_data[32],
        "alcohol_free_nights_per_week": raw_data[33],
        "cups_of_water_per_day": raw_data[34],
        "avoid_processed_foods": raw_data[35],
        "interested_in_nutrition_plan": raw_data[36],
        "can_follow_weekly_meal_plans": raw_data[37],
        "can_carry_out_food_preparation": raw_data[38],
        "diet_type": raw_data[39],
        "willing_to_eat": raw_data[40],
        "meals_per_day": raw_data[41],
        "daily_meals_include": raw_data[42],
        "food_intolerances_allergies": raw_data[43],
        "foods_you_crave": raw_data[44],
        "drink_sugary_drinks": raw_data[45],
        "interested_in_fitness_plan": raw_data[46],
        "fitness_plan_type": raw_data[47],
        "restorative_exercises": raw_data[48],
        "challenging_exercises": raw_data[49],
        "exercises_willing_to_do": raw_data[50],
        "currently_exercising": raw_data[51],
        "exercise_schedule": raw_data[52],
        "exercise_time_per_day": raw_data[53],
        "training_location": raw_data[54],
        "has_personal_trainer": raw_data[55],
        "personal_trainer_frequency": raw_data[56],
        "regular_yoga_practice": raw_data[57],
        "flexibility_rating": raw_data[58],
        "increase_flexibility": raw_data[59],
        "strength_rating": raw_data[60],
        "increase_strength": raw_data[61],
        "fitness_rating": raw_data[62],
        "increase_fitness": raw_data[63],
        "physical_injuries": raw_data[64],
        "injury_details": raw_data[65],
        "mindfulness_stress_management_plan": raw_data[66],
        "bedtime": raw_data[67],
        "fall_asleep_easily": raw_data[68],
        "wake_up_during_night": raw_data[69],
        "difficult_to_get_back_to_sleep": raw_data[70],
        "average_sleep_hours": raw_data[71],
        "wake_up_time": raw_data[72],
        "wake_up_feeling_rested": raw_data[73],
        "morning_energy_rating": raw_data[74],
        "challenging_to_unwind_after_work": raw_data[75],
        "unwind_methods": raw_data[76],
        "mental_health_rating": raw_data[77],
        "incorporate_mindfulness": raw_data[78],
        "incorporate_stress_management": raw_data[79],
        "incorporate_stretches": raw_data[80],
        "incorporate_meditation": raw_data[81],
        "enjoy_walking_for_exercise": raw_data[82],
        "walking_time_per_day": raw_data[83],
        "wellbeing_changes": raw_data[84],
        "smoking": raw_data[85],
        "quit_smoking_desire": raw_data[86],
        "taking_supplements": raw_data[87],
        "supplement_details": raw_data[88],
        "on_medication": raw_data[89],
        "medication_details": raw_data[90],
        "digestive_health_problems": raw_data[91],
        "digestive_health_details": raw_data[92],
        "diagnosed_health_concerns": raw_data[93],
        "health_concern_details": raw_data[94],
        "under_guidance_of_naturopath_dietician_nutritionist": raw_data[95],
        "guidance_details": raw_data[96],
        "questions_or_concerns": raw_data[97]
    }

    return data_map
